### ISSUE TITLE
Support `Instant:now()`

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/near-bindgen#4]
`Instant::now()` should be taking the time from the corresponding block that every validator agrees on, oppose the returning the actual current time at which the contract is executed.

**Comment by ailisp** [comment]
This needs to be implement in primitives. @bowenwang1996 recently did some work to prevent a time consensus related attack: https://github.com/nearprotocol/nearcore/pull/1382. If nearcore has a `blockchain now()` primitive (seems hard), this kind of attack would not be possible

**Comment by bowenwang1996** [comment]
Block timestamp is exposed now but is not super reliable. @ailisp I don't understand what you mean. The attack is not related to smart contract in anyway.

**Comment by nearmax** [comment]
This issue is more about problems of interfacing guest and host in Wasm rather than how we compute it in blockchain layer. The problem with calling system-like functions in Wasm is that they either will attempt to call a syscall (and panic if not exposed) or just panic if not implemented, depending on which wasm target we are compiling this for, see relevant discussion: https://github.com/rust-lang/rust/issues/48564

At the time of creating this issue I thought this would be useful however now I think it is not necessary, since it seems developers are comfortable with accessing stuff through `env::*`.

**Comment by nearmax** [comment]
That's why I am closing it.
