### ISSUE TITLE
./build.sh produces non optimized output which is too large to deploy, if copied

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/near-bindgen#59]
starting in examples/status-message:

modify Cargo.toml to have near-bindgen = "0.3.10"

after that:

rm res/*
cd ../../..
mkdir repro
cd repro
cp -r ../near-bindgen/examples/status-message/* .
rustup override set stable
rustup target add wasm32-unknown-unknown
./build.sh 

when that finishes: 
ls -lh res 
-rwxr-xr-x  1 evgueniadegtiareva  staff   1.8M Jan 23 14:56 status_message.wasm

1.8M is too large to deploy

**Comment by nearmax** [comment]
The way you are copying the files loses `.cargo` folder that configures compiler to use optimizations.

**Comment by janedegtiareva** [comment]
Should we update the build files to use RUSTFLAGS='-C link-arg=-s' cargo build --target wasm32-unknown-unknown --release so that it's less likely a developer will end up in this situation?

**Comment by nearmax** [comment]
The developer can just as likely lose `build.sh` file.

**Comment by nearmax** [comment]
But, I think it is a good idea to get rid of `.cargo` since we already have `build.sh`.

**Comment by janedegtiareva** [comment]
https://github.com/nearprotocol/near-bindgen/pull/60
