### ISSUE TITLE
contracts don't work if we use serde_json = "1.0.0"

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/near-bindgen#64]
Steps to repro: use contract from https://github.com/nearprotocol/create-near-app/pull/65
use  serde_json = "1.0.0"
deploy app and run (yarn start)

when running app, get GasInstrumentation failure (see screenshot)
<img width="781" alt="Screen Shot 2020-01-27 at 12 16 17 PM" src="https://user-images.githubusercontent.com/1320689/73188145-2df49d80-4101-11ea-948d-b75bdca6dd3e.png">

**Comment by nearmax** [comment]
What node version are you using? If you are using docker image then we don't have floats enabled there yet, which is what needed for using serde_json 1.0.0. This will be fixed in the next version.

**Comment by janedegtiareva** [comment]
Testnet: 
{"chain_id":"testnet","rpc_addr":"0.0.0.0:8080","sync_info":{"latest_block_hash":"DRzfUJHw2NjoFF3mZaQieynQ5rtaG3fb43zbFQSpiEyd","latest_block_height":636218,"latest_block_time":"2020-01-27T19:31:35.350132049Z","latest_state_root":"BWFyPZ12pUXZiLvF2CaVmF7hvJC25wNJrbaCkgSKHToU","syncing":false},"validators":[{"account_id":"far","is_slashed":false}],"version":{"build":"1a0ea717-modified","version":"0.4.12"}}

Let's hold off using 1.0.0 in create-near-app until the fix is rolled out everywhere. I want to use create-near-app at the hackathon in order to test drive the experience.
