### ISSUE TITLE
Passing empty method_names in add_access_key fails

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-bindgen#91]
When creating promise with adding access key, there is no way to allow for no method name restriction.
Passing empty bytes doesn't work, results in EmptyMethodName error.

Repro:
```
        Promise::new(env::current_account_id()).add_access_key(
            pk,
            ACCESS_KEY_ALLOWANCE,
            env::current_account_id(),
            vec![]
        );
```

**Comment by nearmax** [comment]
Full access key is added using `add_full_access_key`. Moving to the documentation columns since this requires clarification in our documentation.

**Comment by nearmax** [comment]
Assigning to @amgando since this might be a piece of a larger effort of improving near-bindgen documentation.

**Comment by evgenykuzyakov** [comment]
Created an issue in nearcore: https://github.com/nearprotocol/nearcore/issues/2183

**Comment by evgenykuzyakov** [comment]
Reopening, because we'll have to rebuild `near-bindgen` once logic is fixed and published.

**Comment by ilblackdragon** [comment]
@nearmax Eugene fixed it, but want to make sure you are on the same page that this is a bug not a documentation issue - the issue is that the contract specific but not restricted by methods function access key could not be added.
