### ISSUE TITLE
Example README not working: cross-contract high level

### ISSUE THREAD

**Issue by mikedotexe** [nearprotocol/near-bindgen#97]
Tried following the README for https://github.com/nearprotocol/near-bindgen/tree/master/examples/cross-contract-high-level

A few things went wrong. One of them seems to be this:

`near create_account cross_contract --masterAccount=test_near  --initialBalance 10000000`

It seems that the `initialBalance` flag now refers to NEAR tokens, _not_ yoctoNEAR.

Replacing 10000000 with 1 succeeded.

The next line also has issues:

`near deploy --accountId=cross_contract --wasmFile=../examples/cross-contract-high-level/res/cross_contract_high_level.wasm`

it should be `--wasmFile=./res/cross_contract_high_level.wasm` instead.

Then the next line also doesn't work:

`near call cross_contract deploy_status_message "{\"account_id\": \"status_message\", \"amount\":1000000000000000}" --accountId=test_near`

I replaced 1000000000000000 with 1, and also the `accountId` and `cross_contract` with my respective accounts. After that I am getting:

**link error: data segment does not fit**
```
near call nfcc001 deploy_status_message "{\"account_id\": \"status_message\", \"amount\":1}" --accountId=near-friend
configPath:  /Users/mike/near/near-bindgen/examples/cross-contract-high-level/src/config
[WARNING] Didn't find config at /Users/mike/near/near-bindgen/examples/cross-contract-high-level/src/config, using default shell config
{ networkId: 'default',
  nodeUrl: 'https://rpc.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.nearprotocol.com' }
(node:21188) ExperimentalWarning: The fs.promises API is experimental
Scheduling a call: nfcc001.deploy_status_message({"account_id": "status_message", "amount":1})
aloha: signAndSendTransaction in account.js
Error:  { Error: Transaction 3F3k41ZVzMvxMbM598vEAwnLtwrhZEiJ6FLJCn6MpkWa failed. link error: data segment does not fit
    at Account.signAndSendTransaction (/Users/mike/.nvm/versions/node/v10.16.0/lib/node_modules/near-shell/node_modules/nearlib/lib/account.js:85:23)
    at process._tickCallback (internal/process/next_tick.js:68:7) type: 'ActionError::FunctionCallError' }
```

^ That's hard to read so here's a screenshot with colors:

<img width="761" alt="Screenshot 2020-02-24 16 23 59" src="https://user-images.githubusercontent.com/1042667/75203093-14576d80-5722-11ea-8df0-f45504785762.png">

**Comment by nearmax** [comment]
> It seems that the initialBalance flag now refers to NEAR tokens, not yoctoNEAR.

Seems like changes to near-shell broken near-bindgen documentation. CC @damons , @bowenwang1996 , @ailisp , @vgrichina , @janedegtiareva 

> it should be --wasmFile=./res/cross_contract_high_level.wasm instead.

The documentation does not explain that paths are relative and the developer has to decide themselves what this path should be like.

> link error: data segment does not fit

I cannot reproduce it. It works on my machine. 
near-shell version: 0.20.1
And the most recent nearprotocol/nearcore:latest

**Comment by mikedotexe** [comment]
I am no longer seeing this issue, closing.
